WoodMasters2/Controllers/CommentController.cs
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using WoodMasters2.Core.Constants;
using WoodMasters2.Core.Contracts;
using WoodMasters2.Core.Data.Entities;
using WoodMasters2.Core.Models.Comments;

namespace WoodMasters2.Controllers
{
    /// <summary>
    /// Comments controller
    /// </summary>
    public class CommentController : BaseController
    {
        private readonly ICommentService commentService;
        private readonly IMasterPieceService masterPieceService;
        /// <summary>
        /// Injecting MasterPieceService and CommentService
        /// </summary>
        /// <param name="_masterPieceService"></param>
        /// <param name="_commentService"></param>
        public CommentController(IMasterPieceService _masterPieceService,ICommentService _commentService)
        {
            masterPieceService = _masterPieceService;
            commentService = _commentService;            
        }

        /// <summary>
        /// Post method for showing all comments for a MasterPiece
        /// </summary>
        /// <param name="masterPieceId"></param>
        /// <returns></returns>
       //[HttpPost]        
        public async Task<IActionResult> AllComments(int masterPieceId)
        {
            var model = await commentService.GetAllCommentsAsync(masterPieceId);
            return View(model);
        }
        /// <summary>
        /// Get method for Add
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public IActionResult Add()
        {

            return View();
        }
        /// <summary>
        /// Post method for Add
        /// </summary>
        /// <param name="model"></param>
        /// <param name="masterPieceId"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> Add(CommentFormModel model, int masterPieceId)
        {
            if (!ModelState.IsValid)
            {
                TempData[MessageConstant.ErrorMessage] = "You entered some wrong data. Try again!";
                return View(model);
            }
            var userId = User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.NameIdentifier)?.Value;
            
            await commentService.AddCommentAsync(model, userId!,masterPieceId);

            TempData[MessageConstant.SuccessMessage] = "Your comment has been published!";

            return RedirectToAction(nameof(AllComments), new { masterPieceId });
        }


        /// <summary>
        /// Get method for Edit
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var model = await commentService.GetEditCommentAsync(id);
            return View(model);
        }


        /// <summary>
        /// Post method for editing comment
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> Edit(EditCommentViewModel model)
        {
            if (!ModelState.IsValid)
            {
                TempData[MessageConstant.ErrorMessage] = "Please try again!";
                return View(model);
            }
            await commentService.EditCommentAsync(model);
            int masterPieceId = model.MasterPieceId;
            TempData[MessageConstant.SuccessMessage] = "Your comment has been edited!";
            return RedirectToAction(nameof(AllComments), new {masterPieceId });
                        
        }
        
        /// <summary>
        /// Deleting a comment method
        /// </summary>
        /// <param name="commentId"></param>        
        /// <param name="masterPieceId"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> Delete(int commentId, int masterPieceId)
        {
            await commentService.DeleteAsync(commentId, masterPieceId);
            TempData[MessageConstant.WarningMessage] = "Your comment has been deleted!";
            return RedirectToAction(nameof(AllComments), new { masterPieceId });
        }
    }
}

WoodMasters2/Controllers/MasterPieceController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

using System.Security.Claims;
using System.Web;
using WoodMasters2.Core.Constants;
using WoodMasters2.Core.Contracts;
using WoodMasters2.Core.Data;
using WoodMasters2.Core.Data.Entities;
using WoodMasters2.Core.Models.MasterPieces;

namespace WoodMasters2.Controllers
{/// <summary>
/// MasterPiece controller
/// </summary>
    [Authorize]
    public class MasterPieceController : BaseController
    {
        private readonly IMasterPieceService masterPieceService;
        
        

        /// <summary>
        /// Injecting MasterPieceService and context
        /// </summary>
        
        /// <param name="_masterPieceService"></param>
        public MasterPieceController(IMasterPieceService _masterPieceService)
        {
            masterPieceService = _masterPieceService;
            
        }



        /// <summary>
        /// AllCrafts method
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        [AllowAnonymous]
        public IActionResult All([FromQuery] AllMasterPiecesQueryModel query)
        {
            var queryResult = masterPieceService.AllCrafts(
                query. Category,
                query.SearchKey,
                query.Sorting,
                query.CurrentPage,
                AllMasterPiecesQueryModel.CraftsPerPage);
            query.TotalCrafts = queryResult.Result.TotalMasterPieces;
            query.Crafts = queryResult.Result.CraftPieces;
            var masterPieceCategories = this.masterPieceService.AllCategoriesNames();
            query.Categories = masterPieceCategories;

                return View(query);
        }
            



        /// <summary>
        /// Get method for the last 3 MasterPieces
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var model = await masterPieceService.GetLast3MasterPiecesAsync();
            if (User?.Identity?.IsAuthenticated == false)
            {

                TempData[MessageConstant.SuccessMessage] = "Welcome! Please Log-in!";
                
            }
            return View(model);
        }

        /// <summary>
        /// Get method for the Details of a MasterPiece
        /// </summary>
        /// <param name="masterPieceId"></param>
        /// <returns></returns>
        [HttpGet]
        
        public async Task<IActionResult> Details(int masterPieceId)
        {
            var model = await masterPieceService.GetMasterPieceViewByIdAsync(masterPieceId);
            

            return View(model);
        }



        /// <summary>
        /// Add MasterPiece control on GET
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public async Task<IActionResult> Add()
        {
            var model = new AddMasterPieceViewModel()
            {
                Categories = await masterPieceService.GetCategoriesAsync(),
                Woods = await masterPieceService.GetWoodsAsync()                
            };


            return View(model);
        }
        /// <summary>
        /// Add MasterPiece on POST
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> Add(AddMasterPieceViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            if ((await masterPieceService.CategoryExists(model.CategoryId)) == false)
            {
                ModelState.AddModelError(nameof(model.CategoryId), "Category does not exist");
            }
            if ((await masterPieceService.WoodExists(model.WoodId)) == false)
            {
                ModelState.AddModelError(nameof(model.WoodId), "Wood type does not exist");
            }
            var userId = User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.NameIdentifier)?.Value;
            await masterPieceService.AddMasterPieceAsync(model, userId!);
            TempData[MessageConstant.SuccessMessage] = "Masterpiece added!";
            return RedirectToAction(nameof(All));

        }
        
        /// <summary>
        /// Add to Favorites List
        /// </summary>
        /// <param name="masterPieceId"></param>
        /// <returns></returns>
        [HttpGet]
        public async Task<IActionResult> AddToFavorites(int masterPieceId)
        {

            var userId = User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.NameIdentifier)?.Value;
            await masterPieceService.AddMasterPieceToFavoritesAsync(masterPieceId, userId!);
            TempData[MessageConstant.SuccessMessage] = "Masterpiece added to Favorites!";

            return RedirectToAction(nameof(All));
        }
        /// <summary>
        /// Get the list of Favorites
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public async Task<IActionResult> Favorites()
        {
            var userId = User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.NameIdentifier)?.Value;
            var model = await masterPieceService.GetFavoritesAsync(userId!);

            return View(model);
        }
        /// <summary>
        /// Get the list of Owned MasterPieces
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public async Task<IActionResult> Mine()
        {
            var userId = User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.NameIdentifier)?.Value;
            var model = await masterPieceService.GetMineAsync(userId!);

            return View("Mine",model);
        }

        /// <summary>
        /// Remove a MasterPiece from Favorites list
        /// </summary>
        /// <param name="masterPieceId"></param>
        /// <returns></returns>
       
        public async Task<IActionResult> Remove(int masterPieceId)
        {
            var userId = User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.NameIdentifier)?.Value;
            await masterPieceService.RemoveMasterPieceFromFavoritesAsync(masterPieceId, userId!);
            TempData[MessageConstant.WarningMessage] = "Masterpiece removed from Favorites!";
            return RedirectToAction(nameof(Favorites));
        }

        /// <summary>
        /// Deleteing MasterPiece from Master's collection
        /// </summary>
        /// <param name="masterPieceId"></param>
        /// <returns></returns>
         
        public async Task<IActionResult> Delete(int masterPieceId)
        {
            await masterPieceService.DeleteAsync(masterPieceId);
            TempData[MessageConstant.ErrorMessage] = "Masterpiece deleted!";
            return RedirectToAction(nameof(All));

        }/// <summary>
        /// Get for Editing a MasterPiece
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var model = await masterPieceService.GetEditMasterPieceAsync(id);
            return View(model);
        }
        /// <summary>
        /// Post for Editing a MasterPiece
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> Edit(EditMasterPieceViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            await masterPieceService.EditMasterPieceAsync(model);
            TempData[MessageConstant.SuccessMessage] = "Masterpiece edited!";
            return RedirectToAction(nameof(Mine));
        }
        
        
    }
}

WoodMasters2/Views/MasterPiece/All.cshtml
@using WoodMasters2.Core.Models.MasterPieces
@model AllMasterPiecesQueryModel
@{
    ViewBag.Title = "All Masterpieces";
}

<head>
<style>
body  {
  background-image: url("/Images/all-background.jpeg");
  background-color: #cccccc;
}
</style>
</head>
<hr class="border border-warning border-2 opacity-75">

<h2 class="text-center text-white">@ViewBag.Title</h2>
<hr class="border border-warning border-3 opacity-75">

<form method="get">
<div class="row">
<div class="form-group col-md-3 d-flex justify-content-between">
<div class="form-group">
<label class="text-white" asp-for="Category"></label>
<select asp-for="Category"class="form-control">
<option value="">AllCraft</option>
                    @foreach (var category in Model.Categories)
                    {
<option value="@category">@category</option>
                    }
</select>
</div>
</div>

<div class="form-group col-md-3">
<label class="text-white" asp-for="SearchKey"></label>
<input asp-for="SearchKey"class="form-control"placeholder="...">
</div>

<div class="form-group col-md-3 ">
<div class="form-group">
<label class="text-white" asp-for="Sorting"></label>
<select asp-for="Sorting"class="form-control">
<option value="0">Newest first</option>
<option value="1">Price(ascending)</option>
<option value="2">Votes(descending)</option>
</select>
</div>
</div>

<div class="col-md-3">
<div class="form-group mt-4 p-0">
<input type="submit"value="Search"class="btn btn-success"/>
</div>
</div>
</div>
</form>
<br />

@if (!Model.Crafts.Any())
{
<h2 class="text-center">No crafts found by the given criteria!</h2>
}

<div class="row">
    @foreach (var masterPiece in Model.Crafts)
    {
     <partial name="_MasterPiecePartial"model="@masterPiece"/>
    }
</div>
@{
var previousPage = Model.CurrentPage - 1;
if (previousPage < 1)
    {
        previousPage = 1;
    }

var maxPage = Math.Ceiling((double)Model.TotalCrafts /AllMasterPiecesQueryModel.CraftsPerPage);
}

<div class="row mb-5">
<div class="col-md-6 d-grid gap-2 d-md-flex justify-content-md-start">
<a class="btn btn-warning @(Model.CurrentPage == 1 ? "disabled" : string.Empty)"
asp-controller="MasterPiece"
asp-action="All"
asp-route-currentPage="@previousPage"
asp-route-category="@Model.Category"
asp-route-searchTerm="@Model.SearchKey"
asp-route-sorting="@((int)Model.Sorting)"><<</a>
</div>

    @{
var shouldButtonBeDisabled = Model.CurrentPage == maxPage ||
        !Model.Crafts.Any();
    }

<div class="col-md-6 d-grid gap-2 d-md-flex justify-content-md-end">
<a class="btn btn-warning
           @(shouldButtonBeDisabled ? "disabled" : string.Empty)"
asp-controller="MasterPiece"
asp-action="All"
asp-route-currentPage="@(Model.CurrentPage + 1)"
asp-route-category="@Model.Category"
asp-route-searchTerm="@Model.SearchKey"
asp-route-sorting="@((int)Model.Sorting)">>></a>
</div>
</div>

@section Scripts {

    
    <script type="text/javascript">
        
      $(function () {
        $("img.rating").mouseover(function () {
            giveRating($(this), "FilledStar.gif");
            $(this).css("cursor", "pointer");
        });

        $("img.rating").mouseout(function () {
            giveRating($(this), "EmptyStar.gif");
            refilRating($(this));
        });
        $("img.rating").click(function (e) {
           
            $(this).css('color', 'red');
           
            // call ajax methods to update database
            var url = "/Rating/PostRating?rating=" + parseInt($(this).attr("id")) + "&mid=" + parseInt($(this).attr("mid"));
            $.get(url, null, function (data) {
                $(e.currentTarget).closest('div').find('div.result').text(data).css('color', 'red')
            });
        });
    });
    function giveRating(img, image) {
        img.attr("src", "/Images/" + image)
            .prevAll("img.rating").attr("src", "/Images/" + image);
    }
    function refilRating(img1)
    {
        var rt = $(img1).closest('div').find("span.avr").text();
        var img = $(img1).closest('div').find("img[id='" + parseInt(rt) + "']");
        img.attr("src", "/Images/FilledStar.gif").prevAll("img.rating").attr("src", "/Images/FilledStar.gif");
    }    
     
</script>
}

WoodMasters2/Views/MasterPiece/Details.cshtml
@using WoodMasters2.Core.Constants
@using WoodMasters2.Core.Models.MasterPieces
@model MasterPieceViewModel
@{
    ViewBag.Title = "Details";
}

<head>
<style>
body  {
  background-image: url("/Images/all-background.jpeg");
  background-color: #cccccc;
}
</style>
</head>
<hr class="border border-warning border-2 opacity-75">

<h2 class="text-center text-white">@ViewBag.Title</h2>
<hr class="border border-warning border-3 opacity-75">

<div class="container"style="display:inline">
<div class="row">
<div class="col-4">
<img class="card-img-top mb-3"style="width: 20rem;"
src="@Model.ImageURL"alt="MasterPiece Image">
<div class="form-inline">
                @if (User?.Identity?.IsAuthenticated ?? false)
                {
                    <a asp-controller="Comment" asp-action="AllComments"  asp-route-masterPieceId="@Model.Id"
                     class="btn btn-secondary">Comments</a> 

                   if((User?.Identity?.Name == Model.Master) || (User?.IsInRole(RoleConstants.Admin) == true))
                    {
                        <a class="btn btn-warning"asp-controller="MasterPiece"asp-action="Edit"
                        asp-route-id="@Model.Id">Edit</a>

                        <a asp-controller="MasterPiece"asp-action="Delete"
                        asp-route-masterPieceId="@Model.Id" method="post">
                            <input class="btn btn-danger"type="submit" value="Delete"
                                 onclick="return confirm('Are you sure you want to delete the masterpiece: @Model.Name')"/>
                        </a>
                   
                    } 
                }
                
</div>
</div>
<div class="card col-8 border-0">
<p style="font-size:25px;"><u><b>@Model.Name</b></u></p>
<p>Category: <b>@Model.Category</b></p>
<p>Crafted by: <b>@Model.Master</b></p>
<p>
                Price Per Piece:
<b>@String.Format("{0:f2}", Model.Price) </b>USD
</p>
<p><b>@Model.Quantity</b> more piece(s) available</p>
<p class="mb-1">Width: <b>@Model.Width</b> cm</p>
<p class="mb-1">Length: <b>@Model.Length</b> cm</p>
<p class="mb-1">Depth: <b>@Model.Depth</b> cm</p>

<h6>@Model.Description</h6>
<h6>Made of <b>@Model.Wood</b> wood</h6>

            
</div>
<p></p>
<div class="card"style="width: 18rem;">
<div class="card-body">
<h5 class="card-title  text-primary center"><b><u>Crafter Info</u></b></h5>
<p class="card-text">Full Name: <b> @Model.MasterFullName</b></p>
<p class="card-text">Experience: <b> @Model.MasterExperience</b></p>
<p class="card-text">Email: <b> @Model.MasterEmail</b></p>
<p class="card-text">Phone Number: <b>@Model.MasterPhone</b></p>
<p class="card-text">Address: <b>@Model.MasterAddress</b></p>
</div>
</div>
</div>


</div>

WoodMasters2/Views/MasterPiece/Favorites.cshtml
@using WoodMasters2.Core.Models.MasterPieces

@model IEnumerable<MasterPieceViewModel>

@{
ViewBag.Title = "Favorite MasterPieces";
}
<head>
<style>
body  {
  background-image: url("/Images/fav-background.jpg");
  background-color: #cccccc;
}
</style>
</head>
<hr class="border border-primary border-2 opacity-100">
<h2 class="text-center text-primary">@ViewBag.Title</h2>
<hr class="border border-primary border-3 opacity-100">


<div class="text-center row">
    @foreach (var mp in Model)
    {
        <div class="card col-4"style="width: 25rem; ">
        <img class="card-img-top"style="width: 20rem;"
        src="@mp.ImageURL"alt="MasterPiece Image">
        <div class="card-body">

         <h5 class="card-title mt-1"><u><b>@mp.Name</b></u></h5>
                <h6>Category: <b>@mp.Category</b></h6>
 <h6>Made of <b>@mp.Wood</b> wood</h6>
 <h6>@mp.Description</h6>
 <p class="mb-1">Width/Length/Depth: <b>@mp.Width / @mp.Length / @mp.Depth</b> cm</p>
<h6>Master: <b>@mp.Master</b></h6>
<h6>Price :<b>@String.Format("{0:f2}", mp.Price) USD</b></h6>
<h6><b>@mp.Quantity</b> more piece(s) available</h6>
                
        </div>

        <a asp-controller="Comment" asp-action="AllComments"  asp-route-masterPieceId="@mp.Id"
                class="btn btn-secondary">Comments</a> 
        <a asp-controller="MasterPiece" asp-action="Remove"  asp-route-masterPieceId="@mp.Id"
                class="btn btn-danger">Remove from Favorites
                <onclick="return confirm('Are you sure you want to remove MasterPiece: @mp.Name from your Favorites?')"/></a> 
        
      
        </div>
    }
</div>

WoodMasters2/Views/MasterPiece/Index.cshtml
@using WoodMasters2.Core.Models.MasterPieces
@model IEnumerable<MasterPieceViewModel>

@{
    ViewData["Title"] = "Home Page";
var masterPieces = Model.ToList();
}
<head>
<style>
body  {
  background-image: url("/Images/home-bg.jpg");
  background-color:dimgrey;
}
</style>
</head>
<div class="text-center p-1 bg-muted">
    <h1 class="display-1 center"><b>Welcome to your WoodWorld!</b></h1>
    </div>
@if (!masterPieces.Any())
{
    
    <p class="lead">
                There are no items to show in the system currently available
                so why don't you just add one?
    </p>
    <hr class="my-4">
    <p class="lead">
                @if (User?.Identity?.IsAuthenticated ?? false)
                {
                    <a asp-controller="MasterPiece"asp-action="Add"class="btn btn-primary btn-lg"
                    role="button">Add a Master Piece</a>
                }
    </p>
    
}

<div class="mb-5"></div>

<div id="carouselExampleControls"class="carousel slide"data-bs-ride="carousel">
<div class="carousel-inner">
        @for (int i = 0; i < masterPieces.Count(); i++)
        {
            var masterPiece = masterPieces[i];
            <div class="carousel-item @(i == 0 ? "active" : string.Empty)">
            <img class="d-block w-100"style="height:500px"
            src="@masterPiece.ImageURL"alt="@masterPiece.Name">
            <div class="carousel-caption d-none d-md-block">
            @if (User?.Identity?.IsAuthenticated ?? false)
                {
                <h5>
                     <a class="btn btn-primary"asp-controller="MasterPiece"asp-action="Details"
                     asp-route-masterPieceId="@masterPiece.Id"> @masterPiece.Name</a>
                </h5>
                }
            </div>
            </div>
        }
</div>
<button class="carousel-control-prev"type="button"data-bs-target="#carouselExampleControls"data-bs-slide="prev">
<span class="carousel-control-prev-icon"aria-hidden="true"></span>
<span class="visually-hidden">Previous</span>
</button>
<button class="carousel-control-next"type="button"data-bs-target="#carouselExampleControls"data-bs-slide="next">
<span class="carousel-control-next-icon"aria-hidden="true"></span>
<span class="visually-hidden">Next</span>
</button>
</div>

WoodMasters2/Views/MasterPiece/Mine.cshtml
@using WoodMasters2.Core.Models.MasterPieces
@model IEnumerable<MasterPieceViewModel>

@{
ViewBag.Title = "Owned MasterPieces";
}
<head>
<style>
body  {
  background-image: url("/Images/mine-background.jpg");
  background-color: #cccccc;
}
</style>
</head>
<hr class="border border-dark border-2 opacity-75">
<h1 class="text-center">@ViewBag.Title</h1>
<hr class="border border-dark border-3 opacity-75">


<div class="text-center row">
    @foreach (var mp in Model)
    {
        <div class="card col-4"style="width: 20rem; ">
            <img class="card-img-top"style="width: 18rem;"
            src="@mp.ImageURL"alt="MasterPiece Image">
            <div class="card-body">

                <h5 class="card-title mt-1"><b><u>@mp.Name</u></b></h5>
                <p class="mb-1">Category: <b>@mp.Category</b></p>                
                <p class="mb-1">Width/Length/Depth[cm]:<b>@mp.Width/@mp.Length/@mp.Depth</b> </p>                
                <p class="mb-1">Description: <b>@mp.Description</b></p>
                <p class="mb-1">Wood: <b>@mp.Wood</b></p>
                <p class="mb-0">Price: <b>@mp.Price</b> $</p>
                <p class="mb-1">Quantity: <b>@mp.Quantity</b> pcs.</p>
               
            </div>
                <div class="form-inline">
                        <a class="btn btn-warning"asp-controller="MasterPiece"asp-action="Edit"
                        asp-route-id="@mp.Id">Edit</a>

                        <a asp-controller="MasterPiece"asp-action="Delete"
                        asp-route-masterPieceId="@mp.Id" method="post">
                            <input class="btn btn-danger"type="submit" value="Delete"
                                 onclick="return confirm('Are you sure you want to delete the masterpiece: @mp.Name')"/>
                        </a>
                </div>
        </div>
    }
</div>

WoodMasters2/Views/MasterPiece/_MasterPiecePartial.cshtml
@using WoodMasters2.Core.Models.MasterPieces
@model MasterPieceViewModel

<div class="col-md-4">
<div class="card col-4" style="width: 25rem; ">
<img class="card-img-top center"style="width: 24rem;"src="@Model.ImageURL"alt="MasterPiece Image">
<div class="card-body">
        <div class="card-title mt-1"><u><b>@Model.Name</b></u> 
        
        <br />                    
                        <img src="~/Images/EmptyStar.gif" alt="Star Rating" align="middle" id="1" class="rating" mid="@Model.Id" />
                        <img src="~/Images/EmptyStar.gif" alt="Star Rating" align="middle" id="2" class="rating" mid="@Model.Id" />
                        <img src="~/Images/EmptyStar.gif" alt="Star Rating" align="middle" id="3" class="rating" mid="@Model.Id" />
                        <img src="~/Images/EmptyStar.gif" alt="Star Rating" align="middle" id="4" class="rating" mid="@Model.Id" />
                        <img src="~/Images/EmptyStar.gif" alt="Star Rating" align="middle" id="5" class="rating" mid="@Model.Id" />
                        (<b>@Model.RateCount</b> votes) 
                        @{if (@Model.RateCount > 0)
                            { double a=Math.Round((1.0*@Model.RateTotal / @Model.RateCount), 0,MidpointRounding.AwayFromZero); 
                                <br /><span style="color:black">Average rating : </span>
                                <span class="avr" style="font-size:large">  <b>@a</b> <img src ="~/Images/FilledStar.gif" alt="Star"> </span>
                            } 
                        }
                    <br>
                        <div class="result"></div>
       </div>
 <h6>Category: <b>@Model.Category</b></h6>
 <h6>Made of <b>@Model.Wood</b> wood</h6>
 <h6>@Model.Description</h6>
 <p class="mb-1">Width/Length/Depth: <b>@Model.Width / @Model.Length / @Model.Depth</b> cm</p>
<h6>Master: <b>@Model.Master</b></h6>
<h6>Price :<b>@String.Format("{0:f2}", Model.Price) USD</b></h6>
<h6><b>@Model.Quantity</b> more piece(s) available</h6>

<br/>
<a asp-controller="MasterPiece"asp-action="Details"asp-route-masterPieceId="@Model.Id"
class="btn btn-success">Details</a>
            @if (this.User?.Identity?.IsAuthenticated ?? false)
            {
                @if (User?.Identity?.Name!= Model.Master)
                {                
                <a asp-controller="MasterPiece" asp-action="AddToFavorites" asp-route-masterPieceId="@Model.Id"
                class="btn btn-warning">Add to Favorites</a>                                   
                }
                <a asp-controller="Comment" asp-action="AllComments"  asp-route-masterPieceId="@Model.Id"
                class="btn btn-secondary">Comments</a> 

            }           
</div>
</div>
</div>